---
channel: stable
addons:
  influxdb:
    repository: srsgit/addon-influxdb
    target: influxdb
    image: ghcr.io/srsgit/{arch}-addon-influxdb
  grafana:
    repository: srsgit/addon-grafana
    target: .
    image: ghcr.io/srsgit/{arch}-addon-grafana
